<div id='wr_ap'>
	<link rel='stylesheet' href='<?php echo $url ?>/style_admin.css' type='text/css' />
	<script type='text/javascript' src='<?php echo $url ?>/jquery.js'></script>
	<script type='text/javascript' src='<?php echo $url ?>/jquery.form.js'></script>
	<script type='text/javascript' src='<?php echo $url ?>/admin.js'></script>
	<a href='http://whosright.com' target='_blank' title='WhosRight provides a video-based social forum for you, your friends, and the world to air out your opinions and get an answer to the age-old question of WhosRight.'>
		<img src='../wp-content/plugins/whosright/images/poweredby.png' border='0' style='float: left; margin: 5px; cursor: pointer;' />
	</a>
	<p><a href='javascript:void()' onClick='jQuery(".addpoll_container").toggle(250);jQuery(".addpoll_container input[name=whosright_new_poll]").attr({"value": jQuery(".addpoll_container input[name=whosright_new_poll]").val() == 1 ? 0 : 1});'>Add or Remove Whosright Poll</a><br /><br /><br /></p>
	<div class='addpoll_container' <?php if (!isset($_GET['post']) || get_post_meta($_GET['post'], '_whosright_autogenerated') == 1) { ?>style='display: none' <?php } ?>>
		<form method='post' enctype='multipart/form-data' action='<?php echo $url?>/rpcs/addPoll.php'>
 			<?php if ($poll && $poll['id'] != '') { ?>
				<input type='hidden' name='whosright_poll_id' value='<?php echo $poll['id'] ?>' />
			<?php } else if ($wr_id = get_post_meta($_GET['post'], '_whosright_id', true)) { ?>
				<input type='hidden' name='whosright_poll_id' value='<?php echo $wr_id ?>' />
			<?php } else { ?>
				<input type='hidden' name='whosright_new_poll' value='<?php if (!isset($_GET['post']) || get_post_meta($_GET['post'], '_whosright_autogenerated') == 1) { ?>0<?php } else { ?>1<?php } ?>' />
			<?php } ?>
			<?php 
				$error = get_post_meta($_GET['post'], '_whosright_error', true);
				if ($error) {
					echo '<div style="color: red; font-weight: bold;">Error saving poll: '.$error.'</div>';
					delete_post_meta($_GET['post'], '_whosright_error');
				}
				//var_dump($poll);
			?>
			<table width='100%' cellspacing='5' cellspacing='0'>
				<tr>
					<th colspan='3'>
						Poll title
						<div class='media_preview' style='width: 100%'>
						<?php
							$attach_code = '';
							if ($poll && count($poll['attachments'])) {
								$attach_code = $poll['attachments'][0]['url'];
							} else if ($poll && isset($poll['attach_media'])) {
								$attach_code = $poll['attach_media'];
							}
							if (strlen($attach_code)) {
								if (substr($attach_code, 0, 4) == 'http') {
									echo "<img src='{$attach_code}' border='0' />";
								} else {
									if (strpos($attach_code, "soundcloud.com") != false) {
										echo "<div style='width: 100%; height: 100px'>".stripslashes($attach_code)."</div>";
									} else {
										echo "<div style='width: 320px; height: 250px'>".stripslashes($attach_code)."</div>";
									}
								}
							}
						?>
						</div>
					</th>
				</tr>
				<tr>
					<td width='100%'>
						<input type='text' name='whosright_title' value='<?php echo @$poll['title'] ?>' />
					</td>
					<td width='100'>
						<textarea style='display: none' name='whosright_attach_media'><?php if ($poll && count($poll['attachments'])) { echo $poll['attachments'][0]['url']; } else { echo @$poll['attach_media']; } ?></textarea>
						<input type='button' class='attach_button' value='<?php if ($poll && count($poll['attachments'])) { echo "Media attached" ;} else { echo "Attach media +"; } ?>' />
					</td>
					<td align='right' width='100'>
						<select name="whosright_category">
							<option value="-1">Select Category</option>
							<option value="1" <?php if ($poll && $poll['category'] == 1) { echo "selected"; } ?>>Technology</option>
							<option value="2" <?php if ($poll && $poll['category'] == 2) { echo "selected"; } ?>>Sports</option>
							<option value="3" <?php if ($poll && $poll['category'] == 3) { echo "selected"; } ?>>Entertainment</option>
							<option value="4" <?php if ($poll && $poll['category'] == 4) { echo "selected"; } ?>>Lifestyle</option>
							<option value="5" <?php if ($poll && $poll['category'] == 5) { echo "selected"; } ?>>Politics</option>
							<option value="0" <?php if ($poll && $poll['category'] == 0) { echo "selected"; } ?>>Other</option>
						</select>
					</td>
				</tr>
				<tr>
					<th colspan='3'>Poll description</th>
				</tr>
				<tr>
					<td colspan='3'>
						<textarea name='whosright_description' rows='8' cols='72'><?php echo @$poll['description'] ?></textarea>
					</td>
				</tr>
				<tr>
					<th colspan='3'>Tags</th>
				</tr>
				<tr>
					<td colspan='3'><input type='text' name='whosright_tag_str' value='<?php echo @$poll['tag_str'] ?>' /></td>
				</tr>
				<?php if (count($poll['options'])) { ?>
					<?php foreach ($poll['options'] as $option) { ?>
						<tr>
							<th colspan='3'>
								Option <?php echo $option['option_index'] + 1 ?>
								<div class='media_preview' style='width: 100%'>
									<?php 
										$attach_code = '';
										if (isset($option['attach']) && $option['attach'] != '') { 
											$attach_code = $option['attach'];
										} else if (count($option['attachments'])) {
											$attach_code = $option['attachments'][0]['url'];
										}
										if ($attach_code != '') {
											if (substr($attach_code, 0, 4) == 'http') { 
												echo "<img src='{$attach_code}' border='0' />"; 
											} else {
												if (strpos($attach_code, "soundcloud.com") != false) {
													echo "<div style='width: 100%; height: 100px'>".stripslashes($attach_code)."</div>";
												} else {
													echo "<div style='width: 320px; height: 250px'>".stripslashes($attach_code)."</div>";
												}
											}
										}
									?>
								</div>
							</th>
						</tr>
						<tr class='option'>
							<td>
								<input class='option_text' type='text' name='whosright_option_<?php echo $option['option_index'] + 1 ?>' value='<?php echo $option['title'] ?>' />
							</td>
							<td align='center'>
								<textarea class='option_attach_media' style='display: none; float: right; width: 200px; height: 100px;' name='whosright_attach_media_<?php echo $option['option_index'] + 1 ?>'><?php echo $attach_code; ?></textarea>
								<input type='button' class='attach_option_<?php echo $option['option_index'] + 1 ?> attach_button' value='<?php if ($attach_code != '') { echo "Media Attached"; } else { echo "Attach Media +"; } ?>' />
							</td>
							<td align='right'>
								<input type='button' class='attach_delete_<?php echo $option['option_index'] + 1 ?> delete_button' value='Delete' />
							</td>
						</tr>
					<?php } ?>
				<?php } else { $option_index = 1; while ($option_index < 3) : ?>
					<tr>
						<th colspan='3'>
							Option <?php echo $option_index ?>
							<div class='media_preview'></div>
						</th>
					</tr>
					<tr class='option'>
						<td>
							<input class='option_text' type='text' name='whosright_option_<?php echo $option_index ?>' value='' />
						</td>
						<td align='center'>
							<input class='option_attach_media' type='text' style='display: none; width: 100px'  name='whosright_attach_media_<?php echo $option_index ?>' value='' />
							<input type='button' class='attach_option_<?php echo $option_index ?> attach_button' value='Attach Media +' />
						</td>
						<td align='right'>
							<input type='button' class='attach_delete_<?php echo $option_index ?> delete_button' value='Delete' />
						</td>
					</tr>
				<?php ++$option_index; endwhile; } ?>
				<tr class='end_option'><td colspan='3'></td></tr>
			</table>
			<div class='addpoll_footer' style='width: 100%'>
				<input type='button' name='whosright_add_option' value='Add Option +' />
				<hr />
				<input type='checkbox' id='post_allow_anon' name='whosright_allow_anon' <?php if ($poll['login_required'] == 0) { echo 'checked'; } ?>/>
				<label for='post_allow_anon'>Allow anonymous voting</label>
				<br /><br />
				<input type='checkbox' id='post_advanced_att' name='whosright_post_advanced_att' />
				<label for='post_advanced_att' id='post_advanced_att_label'>Advanced Attachments</label>
				<br /><br />
				<input type='checkbox' id='post_advanced' name='whosright_post_advanced' <?php if ($poll['advanced']) { echo 'checked'; } ?> />
				<label for='post_advanced' id='post_advanced_label'>List Mode</label>
				<br /><br />
				<?php if (count($wr_user['code_groups'])) { ?>
					<select name='whosright_require_code'>
						<option value='0'>Anyone can vote</option>
						<?php foreach ($wr_user['code_groups'] as $grp) { ?>
							<option value="<?php echo $grp['id'] ?>" <?php if ($poll && $poll['require_code'] == $grp['id']) { ?>selected<?php } ?>>Require code: <?php echo $grp['name'] ?></option>
						<?php } ?>
					</select>
				<?php } ?>
				<br /><br />
				<input type='checkbox' id='whosright_hide_results' name='whosright_hide_results' <?php if ($poll && $poll['hide_results']) { ?>checked<?php } ?>/>
				<label for='whosright_hide_results'>Hide results</label>
				<br /><br />
				<input type='checkbox' id='whosright_voting_closed' name='whosright_voting_closed' <?php if ($poll && $poll['voting_closed']) { ?>checked<?php } ?>/>
				<label for='whosright_voting_closed'>Close voting</label>

				<!-- <input type='button' class='submit_button' value='Submit' /> -->
				<!-- <input type='button' class='cancel_button' value='Cancel' /> -->
			</div>
		</form>
	</div>
	<div id='fadeout'></div>
	<div id='attach'>
		<div class='attach_tabs'>
			<div onClick='attach_video()' class='tab tab_attach_video' style="background-image: url('<?php echo $url ?>/tab_attach_video.png');"></div>
			<div onClick='attach_photo()' class='tab tab_attach_photo' style="background-image: url('<?php echo $url ?>/tab_attach_photo.png');"></div>
		</div>

		<div class='tab_content attach_video_content'>
			<p>Insert <img src='<?php echo $url ?>/logo_youtube_small.png' border='0' /> link or embed code</p>
			<input class='youtube_link' type='text' width='100%' name='whosright_youtube_code' />
			
			<div class='video_preview'>
				<center><img src='<?php echo $url ?>/logo_youtube.png' border='0' style='margin-top: 30px' /></center>
			</div>
			
			<span><input class='button rounded_4 submit_button' type='button' value='Submit' /></span>
			<input class='button rounded_4 cancel_button' type='button' value='Cancel' />
			<input class='button rounded_4 remove_button' type='button' value='Remove Media' />
		</div>

		<div class='tab_content attach_photo_content'>
			<p>Upload a photo from your computer <img src='<?php echo $url ?>/icon_photo.png' border='0' /></p>

			<form method='post' enctype='multipart/form-data' action='<?php echo $url ?>/rpcs/uploadAttachment.php'>
				<input type='file' name='whosright_photo' style='width: 100%' />
			</form>

			<div class='photo_preview'>
				<center><img src='<?php echo $url ?>/logo_uploadphoto.png' border='0' style='margin-top: 30px' /></center>
			</div>
			<span><input class='button rounded_4 submit_button' type='button' value='Submit' /></span>
			<input class='button rounded_4 cancel_button' type='button' value='Cancel' />
			<input class='button rounded_4 remove_button' type='button' value='Remove Media' />
		</div>
	</div>
</div>
